- id: auto-jira-commit
  name: Auto Jira commit
  description: Automatically format Git commits with Jira issue key, if available
  entry: auto-jira-commit
  language: python
  stages: [prepare-commit-msg]
  always_run: true
